# Generated by Django 5.0.3 on 2024-04-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ending_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='starting_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
