# Generated by Django 5.0.3 on 2024-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_vehicle_ending_address_vehicle_starting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ending_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ending_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='starting_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='starting_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
